#!/usr/bin/env node
// Post a squad-mcp consolidation result as a review on a GitHub or
// Bitbucket Cloud pull request.
//
// Usage:
//   echo '{...consolidator JSON...}' | node tools/post-review.mjs --pr 42
//   echo '{...}' | node tools/post-review.mjs --pr 42 --dry-run
//   echo '{...}' | node tools/post-review.mjs --pr 42 --request-changes-below 60
//   echo '{...}' | node tools/post-review.mjs --pr 42 --repo owner/name
//   echo '{...}' | node tools/post-review.mjs --pr 31 --platform bitbucket-cloud --repo repos_acgsa/some-repo
//
// Flags:
//   --pr <number>                       PR number on the current repo (required, unless
//                                       --output-format=sarif which writes only the file)
//   --platform <auto|github|bitbucket-cloud>
//                                       Default "auto" — detects from `git remote get-url origin`
//   --repo <a>/<b>                      For github: owner/name. For bitbucket-cloud: workspace/repo-slug.
//                                       Optional when auto-detect succeeds.
//   --request-changes-below <number>    Force `request-changes` if APPROVED w/ score below this
//   --severity-cap <N>                  A.3: cap total expanded findings in the body (drops
//                                       lowest-severity-first; Blockers exempt)
//   --drop-below <Suggestion|Minor|Major>
//                                       A.3: drop everything strictly below this severity FIRST
//   --output-format <markdown|sarif|both>
//                                       A.2: default "markdown". `sarif` writes
//                                       .squad/last-review.sarif.json and SKIPS the PR post.
//                                       `both` writes the SARIF AND posts to the PR.
//   --sarif-path <path>                 Override SARIF output path (default .squad/last-review.sarif.json)
//   --dry-run                           Print what would be sent, do NOT execute (still writes SARIF
//                                       on `sarif`/`both` so CI dry-runs are useful)
//   --no-footer                         Omit the "generated by squad-mcp" footer line
//
// Auth:
//   github           — uses `gh auth` (gh CLI must be installed and logged in)
//   bitbucket-cloud  — uses HTTP Basic with env vars:
//                        SQUAD_BITBUCKET_EMAIL  Atlassian account email
//                        SQUAD_BITBUCKET_TOKEN  Atlassian API token (id.atlassian.com)
//                                               Scope required: pullrequest:write
//
// Exit codes:
//   0 = success (posted, or dry-run produced output)
//   2 = invalid input / missing args
//   3 = gh not installed or not authenticated (github only)
//   4 = gh failed or bitbucket HTTP error — prints stderr / response body
//   5 = bitbucket-cloud credentials missing or empty
//   6 = platform auto-detect failed (no recognised remote)
//   7 = SARIF write failed (filesystem error)
//
// This script lives outside the MCP server (tools/, alongside the commit-msg
// hook) because posting to a PR is a side-effecting operation with auth.
// MCP tools are pure primitives. The skill SKILL.md orchestrates: it gets the
// consolidation JSON from `apply_consolidation_rules`, then invokes this CLI.

import { spawn, spawnSync } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { formatPrReview } from "../dist/format/pr-review.js";
import { formatSarif } from "../dist/format/sarif.js";
import { detectPlatform } from "./_pr-platform.mjs";
import {
  postBitbucketCloudReview,
  BitbucketHttpError,
  BITBUCKET_API_BASE,
} from "./_bitbucket-cloud.mjs";

const args = process.argv.slice(2);

function fail(code, msg) {
  process.stderr.write(`post-review: ${msg}\n`);
  process.exit(code);
}

function parseArgs(argv) {
  const out = {
    pr: null,
    repo: null,
    platform: "auto",
    requestChangesBelow: undefined,
    severityCap: undefined,
    dropBelow: undefined,
    outputFormat: "markdown",
    sarifPath: ".squad/last-review.sarif.json",
    dryRun: false,
    noFooter: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    switch (a) {
      case "--pr":
        out.pr = argv[++i];
        break;
      case "--repo":
        out.repo = argv[++i];
        break;
      case "--platform":
        out.platform = argv[++i];
        if (!["auto", "github", "bitbucket-cloud"].includes(out.platform)) {
          fail(2, `--platform must be one of auto|github|bitbucket-cloud, got "${out.platform}"`);
        }
        break;
      case "--request-changes-below":
        out.requestChangesBelow = Number(argv[++i]);
        if (!Number.isFinite(out.requestChangesBelow)) {
          fail(2, `--request-changes-below requires a number`);
        }
        break;
      case "--severity-cap":
        out.severityCap = Number(argv[++i]);
        if (!Number.isInteger(out.severityCap) || out.severityCap <= 0) {
          fail(2, `--severity-cap requires a positive integer`);
        }
        break;
      case "--drop-below":
        out.dropBelow = argv[++i];
        if (!["Suggestion", "Minor", "Major"].includes(out.dropBelow)) {
          fail(2, `--drop-below must be one of Suggestion|Minor|Major, got "${out.dropBelow}"`);
        }
        break;
      case "--output-format":
        out.outputFormat = argv[++i];
        if (!["markdown", "sarif", "both"].includes(out.outputFormat)) {
          fail(2, `--output-format must be one of markdown|sarif|both, got "${out.outputFormat}"`);
        }
        break;
      case "--sarif-path":
        out.sarifPath = argv[++i];
        if (!out.sarifPath || out.sarifPath.trim() === "") {
          fail(2, `--sarif-path requires a non-empty path`);
        }
        break;
      case "--dry-run":
        out.dryRun = true;
        break;
      case "--no-footer":
        out.noFooter = true;
        break;
      case "--help":
      case "-h":
        process.stdout.write(
          "usage: post-review.mjs [--pr <n>] [--platform auto|github|bitbucket-cloud] " +
            "[--repo a/b] [--request-changes-below N]\n" +
            "                      [--severity-cap N] [--drop-below Suggestion|Minor|Major]\n" +
            "                      [--output-format markdown|sarif|both] [--sarif-path <path>]\n" +
            "                      [--dry-run] [--no-footer]\n" +
            "stdin: JSON output of apply_consolidation_rules\n" +
            "auth (bitbucket-cloud): SQUAD_BITBUCKET_EMAIL + SQUAD_BITBUCKET_TOKEN env vars\n" +
            "--pr is required for markdown/both output. sarif-only writes the file and exits.\n",
        );
        process.exit(0);
        break;
      default:
        fail(2, `unknown flag: ${a}`);
    }
  }
  // --pr is required when we'd post to a PR. SARIF-only runs do not need it.
  if (out.outputFormat !== "sarif") {
    if (!out.pr) fail(2, "--pr <number> is required (unless --output-format=sarif)");
    if (!/^\d+$/.test(out.pr)) fail(2, `--pr must be a positive integer, got "${out.pr}"`);
  } else if (out.pr && !/^\d+$/.test(out.pr)) {
    fail(2, `--pr must be a positive integer, got "${out.pr}"`);
  }
  return out;
}

async function readStdin() {
  return await new Promise((resolve, reject) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => {
      data += chunk;
    });
    process.stdin.on("end", () => resolve(data));
    process.stdin.on("error", reject);
  });
}

function ensureGh() {
  // gh --version is read-only and fast. If it's not installed, error early
  // with a clear message instead of letting the user discover it via spawn ENOENT.
  const r = spawnSync("gh", ["--version"], { encoding: "utf8" });
  if (r.error) {
    if (r.error.code === "ENOENT") {
      fail(3, "gh CLI not found in PATH. Install: https://cli.github.com/manual/installation");
    }
    fail(3, `gh check failed: ${r.error.message}`);
  }
  if (r.status !== 0) {
    fail(3, `gh --version exited ${r.status}: ${r.stderr || r.stdout}`);
  }
}

function runGh(args, body) {
  return new Promise((resolve, reject) => {
    const proc = spawn("gh", args, { stdio: ["pipe", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    proc.stdout.on("data", (d) => (stdout += d));
    proc.stderr.on("data", (d) => (stderr += d));
    proc.on("error", reject);
    proc.on("close", (code) => resolve({ code, stdout, stderr }));
    proc.stdin.on("error", reject);
    // Respect backpressure: if the kernel pipe is full, write() returns false
    // and we must wait for "drain" before continuing. Pre-fix this code wrote
    // a large body without awaiting drain, which on small pipe buffers
    // truncated the body silently (gh exits 0 with the prefix only).
    const ok = proc.stdin.write(body, (err) => {
      if (err) reject(err);
    });
    if (ok) {
      proc.stdin.end();
    } else {
      proc.stdin.once("drain", () => proc.stdin.end());
    }
  });
}

/**
 * Resolve the target platform + repo coordinates. Returns either:
 *   { platform: "github", repo: "owner/name"|null }
 *   { platform: "bitbucket-cloud", workspace, repoSlug }
 * Or exits with code 6 on auto-detect failure.
 */
function resolveTarget(opts) {
  // Honour an explicit --platform; auto-detect when "auto".
  let platform = opts.platform;
  let detected = null;

  if (platform === "auto") {
    detected = detectPlatform("origin", process.cwd());
    if (detected.platform === "unknown") {
      fail(
        6,
        `platform auto-detect failed: ${detected.reason}. ` +
          `Pass --platform <github|bitbucket-cloud> and --repo <a/b>.`,
      );
    }
    platform = detected.platform;
  }

  if (platform === "github") {
    // For github, --repo is optional (gh resolves from cwd if omitted).
    return { platform: "github", repo: opts.repo };
  }

  // bitbucket-cloud — needs workspace + repoSlug.
  let workspace = null;
  let repoSlug = null;

  if (opts.repo) {
    const parts = opts.repo.split("/");
    if (parts.length !== 2 || !parts[0] || !parts[1]) {
      fail(2, `--repo must be "workspace/repo-slug" for bitbucket-cloud, got "${opts.repo}"`);
    }
    workspace = parts[0];
    repoSlug = parts[1];
  } else {
    // Try auto-detect even when --platform was forced (we may not have run it yet).
    if (!detected) detected = detectPlatform("origin", process.cwd());
    if (detected.platform !== "bitbucket-cloud") {
      fail(
        6,
        `bitbucket-cloud target needs --repo <workspace>/<repo-slug> ` +
          `(auto-detect resolved to ${detected.platform}: ${detected.reason || ""})`,
      );
    }
    workspace = detected.workspace;
    repoSlug = detected.repoSlug;
  }

  return { platform: "bitbucket-cloud", workspace, repoSlug };
}

async function postGithub({ pr, repo, action, body }) {
  ensureGh();
  const ghArgs = ["pr", "review", pr, `--${action}`, "--body-file", "-"];
  if (repo) ghArgs.push("--repo", repo);

  const r = await runGh(ghArgs, body);
  if (r.code !== 0) {
    process.stderr.write(`gh ${action} failed (exit ${r.code}):\n${r.stderr}`);
    process.exit(4);
  }
  if (r.stdout) process.stdout.write(r.stdout);
  process.stdout.write(`\nposted: ${action} on PR #${pr} (github)\n`);
}

async function postBitbucket({ pr, workspace, repoSlug, action, body }) {
  const email = process.env.SQUAD_BITBUCKET_EMAIL;
  const apiToken = process.env.SQUAD_BITBUCKET_TOKEN;
  if (!email || !apiToken) {
    fail(
      5,
      `bitbucket-cloud requires SQUAD_BITBUCKET_EMAIL and SQUAD_BITBUCKET_TOKEN env vars. ` +
        `Generate an API token at https://id.atlassian.com/manage-profile/security/api-tokens ` +
        `with scope pullrequest:write.`,
    );
  }
  try {
    const res = await postBitbucketCloudReview({
      workspace,
      repoSlug,
      prId: pr,
      action,
      body,
      email,
      apiToken,
    });
    if (res.commentUrl) process.stdout.write(`${res.commentUrl}\n`);
    for (const w of res.warnings) process.stderr.write(`warning: ${w}\n`);
    process.stdout.write(
      `\nposted: ${action} on PR #${pr} (bitbucket-cloud, ${workspace}/${repoSlug})` +
        (res.approveStatus !== "none" ? ` [${res.approveStatus}]` : "") +
        `\n`,
    );
  } catch (err) {
    if (err instanceof BitbucketHttpError) {
      process.stderr.write(`${err.message}\n`);
      process.exit(4);
    }
    if (err && err.code === "INVALID_INPUT") {
      fail(2, err.message);
    }
    if (err && err.code === "FETCH_UNAVAILABLE") {
      fail(3, err.message);
    }
    throw err;
  }
}

async function main() {
  const opts = parseArgs(args);

  let raw;
  try {
    raw = await readStdin();
  } catch (err) {
    fail(2, `failed to read stdin: ${err.message}`);
  }
  if (!raw || raw.trim() === "") {
    fail(2, "no JSON received on stdin");
  }

  let consolidation;
  try {
    consolidation = JSON.parse(raw);
  } catch (err) {
    fail(2, `invalid JSON on stdin: ${err.message}`);
  }
  if (!consolidation || typeof consolidation !== "object" || !consolidation.verdict) {
    fail(
      2,
      "stdin JSON missing required `verdict` field — expected output of apply_consolidation_rules",
    );
  }

  // SARIF write step. Runs FIRST so that even if PR posting fails or is
  // skipped, the CI artefact lands. Honours --dry-run by writing to disk
  // anyway (the CI artefact is the point — silencing it on dry-run would
  // defeat the use case of "ci-only without posting").
  if (opts.outputFormat === "sarif" || opts.outputFormat === "both") {
    const sarifOptions = {};
    if (opts.repo) sarifOptions.repoLabel = opts.repo;
    const sarif = formatSarif(consolidation, sarifOptions);
    // Containment check (CWE-22): reject paths that escape cwd. Absolute paths
    // and relatives like `../../etc/x` are rejected. This matters when --sarif-path
    // flows from CI config or future .squad.yaml — not just from a trusted local
    // argv. Reject NUL bytes too (defence in depth).
    if (opts.sarifPath.includes("\0")) {
      fail(2, `--sarif-path must not contain NUL bytes`);
    }
    const sarifAbs = path.resolve(process.cwd(), opts.sarifPath);
    const rel = path.relative(process.cwd(), sarifAbs);
    if (path.isAbsolute(rel) || rel === ".." || rel.startsWith(".." + path.sep)) {
      fail(2, `--sarif-path must resolve inside the workspace, got ${opts.sarifPath}`);
    }
    try {
      await fs.mkdir(path.dirname(sarifAbs), { recursive: true });
      await fs.writeFile(sarifAbs, JSON.stringify(sarif, null, 2) + "\n", "utf8");
      process.stdout.write(`sarif: wrote ${sarifAbs}\n`);
    } catch (err) {
      fail(7, `SARIF write failed at ${sarifAbs}: ${err.message}`);
    }
    if (opts.outputFormat === "sarif") {
      // Pure SARIF mode — done. No PR post.
      process.exit(0);
    }
  }

  const target = resolveTarget(opts);

  const formatOptions = {};
  if (typeof opts.requestChangesBelow === "number") {
    formatOptions.requestChangesBelowScore = opts.requestChangesBelow;
  }
  if (opts.repo) formatOptions.repoLabel = opts.repo;
  if (opts.severityCap !== undefined || opts.dropBelow !== undefined) {
    formatOptions.severityBudget = {};
    if (opts.severityCap !== undefined) formatOptions.severityBudget.perPrMax = opts.severityCap;
    if (opts.dropBelow !== undefined) formatOptions.severityBudget.dropBelow = opts.dropBelow;
  }

  const payload = formatPrReview(consolidation, formatOptions);
  let body = payload.body;
  if (opts.noFooter) {
    // Strip the trailing "---\n_Generated by..._\n" footer block. Idempotent.
    body = body.replace(/\n\n---\n[\s\S]*$/, "\n");
  }

  if (opts.dryRun) {
    process.stdout.write(`# DRY RUN — would post to ${target.platform}:\n`);
    if (target.platform === "github") {
      const ghArgs = ["pr", "review", opts.pr, `--${payload.action}`, "--body-file", "-"];
      if (target.repo) ghArgs.push("--repo", target.repo);
      process.stdout.write(
        `gh ${ghArgs.map((a) => (a.includes(" ") ? JSON.stringify(a) : a)).join(" ")} <<'EOF'\n`,
      );
    } else {
      const prBase = `${BITBUCKET_API_BASE}/repositories/${target.workspace}/${target.repoSlug}/pullrequests/${opts.pr}`;
      process.stdout.write(
        `POST ${prBase}/comments\n` +
          (payload.action !== "comment" ? `POST ${prBase}/${payload.action}\n` : ""),
      );
      process.stdout.write(`body:\n`);
    }
    process.stdout.write(body);
    if (target.platform === "github") process.stdout.write(`EOF\n`);
    process.stdout.write(`\n# Action: ${payload.action}\n# Summary: ${payload.summary}\n`);
    process.exit(0);
  }

  if (target.platform === "github") {
    await postGithub({ pr: opts.pr, repo: target.repo, action: payload.action, body });
  } else {
    await postBitbucket({
      pr: opts.pr,
      workspace: target.workspace,
      repoSlug: target.repoSlug,
      action: payload.action,
      body,
    });
  }
}

main().catch((err) => {
  fail(4, `unexpected error: ${err && err.stack ? err.stack : err}`);
});
