#!/usr/bin/env node
// Post a squad-mcp consolidation result as a `gh pr review` on a GitHub PR.
//
// Usage:
//   echo '{...consolidator JSON...}' | node tools/post-review.mjs --pr 42
//   echo '{...}' | node tools/post-review.mjs --pr 42 --dry-run
//   echo '{...}' | node tools/post-review.mjs --pr 42 --request-changes-below 60
//   echo '{...}' | node tools/post-review.mjs --pr 42 --repo owner/name
//
// Flags:
//   --pr <number>                       PR number on the current repo (required)
//   --repo <owner/name>                 Override the repo (else gh resolves from cwd)
//   --request-changes-below <number>    Force `request-changes` if APPROVED w/ score below this
//   --dry-run                           Print the gh command + body, do NOT execute
//   --no-footer                         Omit the "generated by squad-mcp" footer line
//
// Exit codes:
//   0 = success (posted, or dry-run produced output)
//   2 = invalid input / missing args
//   3 = gh not installed or not authenticated
//   4 = gh failed (non-zero) — prints stderr from gh
//
// This script lives outside the MCP server (tools/, alongside the commit-msg
// hook) because posting to GitHub is a side-effecting operation with auth.
// MCP tools are pure primitives. The skill SKILL.md orchestrates: it gets the
// consolidation JSON from `apply_consolidation_rules`, then invokes this CLI.

import { spawn, spawnSync } from "node:child_process";
import { formatPrReview } from "../dist/format/pr-review.js";

const args = process.argv.slice(2);

function fail(code, msg) {
  process.stderr.write(`post-review: ${msg}\n`);
  process.exit(code);
}

function parseArgs(argv) {
  const out = {
    pr: null,
    repo: null,
    requestChangesBelow: undefined,
    dryRun: false,
    noFooter: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    switch (a) {
      case "--pr":
        out.pr = argv[++i];
        break;
      case "--repo":
        out.repo = argv[++i];
        break;
      case "--request-changes-below":
        out.requestChangesBelow = Number(argv[++i]);
        if (!Number.isFinite(out.requestChangesBelow)) {
          fail(2, `--request-changes-below requires a number`);
        }
        break;
      case "--dry-run":
        out.dryRun = true;
        break;
      case "--no-footer":
        out.noFooter = true;
        break;
      case "--help":
      case "-h":
        process.stdout.write(
          "usage: post-review.mjs --pr <n> [--repo owner/name] [--request-changes-below N] [--dry-run] [--no-footer]\n" +
            "stdin: JSON output of apply_consolidation_rules\n",
        );
        process.exit(0);
        break;
      default:
        fail(2, `unknown flag: ${a}`);
    }
  }
  if (!out.pr) fail(2, "--pr <number> is required");
  if (!/^\d+$/.test(out.pr))
    fail(2, `--pr must be a positive integer, got "${out.pr}"`);
  return out;
}

async function readStdin() {
  return await new Promise((resolve, reject) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => {
      data += chunk;
    });
    process.stdin.on("end", () => resolve(data));
    process.stdin.on("error", reject);
  });
}

function ensureGh() {
  // gh --version is read-only and fast. If it's not installed, error early
  // with a clear message instead of letting the user discover it via spawn ENOENT.
  const r = spawnSync("gh", ["--version"], { encoding: "utf8" });
  if (r.error) {
    if (r.error.code === "ENOENT") {
      fail(
        3,
        "gh CLI not found in PATH. Install: https://cli.github.com/manual/installation",
      );
    }
    fail(3, `gh check failed: ${r.error.message}`);
  }
  if (r.status !== 0) {
    fail(3, `gh --version exited ${r.status}: ${r.stderr || r.stdout}`);
  }
}

function runGh(args, body) {
  return new Promise((resolve, reject) => {
    const proc = spawn("gh", args, { stdio: ["pipe", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    proc.stdout.on("data", (d) => (stdout += d));
    proc.stderr.on("data", (d) => (stderr += d));
    proc.on("error", reject);
    proc.on("close", (code) => resolve({ code, stdout, stderr }));
    proc.stdin.write(body);
    proc.stdin.end();
  });
}

async function main() {
  const opts = parseArgs(args);

  let raw;
  try {
    raw = await readStdin();
  } catch (err) {
    fail(2, `failed to read stdin: ${err.message}`);
  }
  if (!raw || raw.trim() === "") {
    fail(2, "no JSON received on stdin");
  }

  let consolidation;
  try {
    consolidation = JSON.parse(raw);
  } catch (err) {
    fail(2, `invalid JSON on stdin: ${err.message}`);
  }
  if (
    !consolidation ||
    typeof consolidation !== "object" ||
    !consolidation.verdict
  ) {
    fail(
      2,
      "stdin JSON missing required `verdict` field — expected output of apply_consolidation_rules",
    );
  }

  const formatOptions = {};
  if (typeof opts.requestChangesBelow === "number") {
    formatOptions.requestChangesBelowScore = opts.requestChangesBelow;
  }
  if (opts.repo) formatOptions.repoLabel = opts.repo;

  const payload = formatPrReview(consolidation, formatOptions);
  let body = payload.body;
  if (opts.noFooter) {
    // Strip the trailing "---\n_Generated by..._\n" footer block. Idempotent.
    body = body.replace(/\n\n---\n[\s\S]*$/, "\n");
  }

  const ghArgs = [
    "pr",
    "review",
    opts.pr,
    `--${payload.action}`,
    "--body-file",
    "-",
  ];
  if (opts.repo) ghArgs.push("--repo", opts.repo);

  if (opts.dryRun) {
    process.stdout.write(`# DRY RUN — would execute:\n`);
    process.stdout.write(
      `gh ${ghArgs.map((a) => (a.includes(" ") ? JSON.stringify(a) : a)).join(" ")} <<'EOF'\n`,
    );
    process.stdout.write(body);
    process.stdout.write(`EOF\n`);
    process.stdout.write(
      `\n# Action: ${payload.action}\n# Summary: ${payload.summary}\n`,
    );
    process.exit(0);
  }

  ensureGh();
  const r = await runGh(ghArgs, body);
  if (r.code !== 0) {
    process.stderr.write(
      `gh ${payload.action} failed (exit ${r.code}):\n${r.stderr}`,
    );
    process.exit(4);
  }
  // gh prints the review URL on success; surface it to the caller.
  if (r.stdout) process.stdout.write(r.stdout);
  process.stdout.write(
    `\nposted: ${payload.action} on PR #${opts.pr} | ${payload.summary}\n`,
  );
}

main().catch((err) => {
  fail(4, `unexpected error: ${err && err.stack ? err.stack : err}`);
});
